### ISSUE TITLE
Documentation outdated or missing

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#1]
## Description
Some of the classes, functions and methods are missing a proper documentation (especially class attributes). This documentation shall be added. Furthermore, the README.md shall be filled with basic content, including a basic description and a link to the docs.

## Tasks
- [ ] Add module and class documentation to
  - [ ] elements (Network, Network Components, ...)
  - [ ] graph
  - [ ] plotter
  - [ ] reader
  - [ ] report
  - [ ] simulator
  - [ ] utils
  - [ ] writer
- [ ] Sphinx docs
  - [ ] Update general OOPNET description
  - [x] Refactor from example-based to topic-based docs
  - [ ] Use [Jupyter notebooks](https://docs.readthedocs.io/en/stable/guides/jupyter.html)
  - [x] Update setup instructions 
  - [ ] Check sphinx docs for completeness
  - [ ] Add static bokeh plot example to Latex output of the plotting section in the user guide 
  - [ ] Add references for models used in the documentation and the corresponding example scripts
- [x] Fill README.md with content

**Comment by tiuri101** [comment]
The documentation is being worked on in the ``docs`` branch and will be merged into ``main``, whenever a part of the docs has been sufficiently improved.
