### ISSUE TITLE
Valve refactoring

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#10]
## Description
There are two issues with the current Valve implementation:
1. The Valve's type is explicitly included as a Valve attribute, although the correct Valve subclasses are used.
2. GPVs currently don't hold a reference to the corresponding Curve but instead uses the Curve's ID.

## Tasks
- [x] Remove valve_type attribute?
- [x] Switch GPVs to reference Curves directly instead of Curve IDs?
- [x] Rename `settings` attribute depending on exact Valve type
