### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#12]
## Description
Errors raised by EPANET are written to the created report files. Parsing them would enable OOPNET to catch and react to these errors. 

## Proposed Solution
Since multiple errors could occur in a single simulation, catching an error should not instantly raise an Exception. Errors should be collected first (e.g., by a manager object), and when all errors are parsed, a single Exception containing all the raised errors should be raised. All possible EPANET errors could be implemented as individual exceptions.

## Tasks
- [x] Implement individual EPANET errors as Python objects
- [x] Implement a container Class to store all raised errors
- [x] Adapt report reader to read errors from report file
