### ISSUE TITLE
OOPNET API

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#14]
## Description
OOPNET provides an API via the `api.py` file, where all classes and functions are directly imported:
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/api.py
A more elegant solution would be to use the `__init__.py` file in all modules and submodules to make parts of the corresponding modules importable. 

## Proposed Solution
Using `__init__.py` files to declare importable functions. This way, not the entire `api.py` has to be imported, but also specific parts can be used.

Getters can now be imported as `from oopnet.utils.getters import *` or just `import oopnet.utils.getters` instead of having `from oopnet.utils.getters.element_lists import get_pattern_ids, ...` (note: `from oopnet.utils.getters.element_lists import *` would be bad practice since this would import absolutely everything from those files, including package imports etc.).

`oopnet.utils.getters` is then imported by the `__init__.py` file in the root directory

To import OOPNET in other scripts, there are three possible ways:
1. `import oopnet`: To call `get_pipe()`, use `oopnet.get_pipe()`
2. `import oopnet as oop`: `oop.get_pipe()`
3. `from oopnet import *`: Same behaviour as before (`get_pipe()`)

Options 1 and 2 would be more pythonic, Option 3 would be shorter when writing code but maybe less readable for other users.

## Tasks
- [x] Create suitable `__init__.py` structure
- [x] Remove `api.py`
- [x] Remove 3rd party packages from `__init__.py`
