### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#15]
## Description
Some files in OOPNET  seem to have not been used for some time. Some of them do not appear to be working at the moment. 

## Proposed Solution
Decide which parts of code to keep and refactor them (maybe move them to suitable classes). Get rid of the rest.

## Affected files and code fragments
- `special_getters.py` (`self` used as function arguments)
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/utils/getters/special_getters.py
- `adddummyjunction()`, `length()` and `sources()` in `utils.py`
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/utils/utils.py#L26
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/utils/utils.py#L84
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/utils/utils.py#L98
- `Report` class in `pandasreport.py` (also see Issue #12)
https://github.com/steffelbauer/oopnet/blob/4d44a3669069137c6e1f1bdffd3f3a72f7996d43/oopnet/report/pandasreport.py#L9

## Tasks
- [x] Implement `split()` method for Pipes, that takes a split_ratio argument (replaces `adddummyjunction()`)
- [x] Implement `get_inflows()` and `get_inflow_ids()` that only returns 
  1. Tanks
  2. Reservoirs
  3. Junctions with a demand <0
- [x] Remove `legnth()` function (it only makes sense with certain coordinate systems/projections)
- [x] Remove `getsourcelist()` 
- [x] Refactor functions in `special_getters.py` and rename file to something more meaningful
