### ISSUE TITLE
Add vertices to links

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#20]
## Description
Vertices can be used to create better visual representations of the model. Currently, vertices are not read from input files, nor are they completely implemented in the OOPNET.

## Tasks
- [x] Add a `vertices` attribute to `Link`
- [x] Implement a reader function
- [x] Implement a writer function
- [x] Adapt `PlotSimulation()` to plot links with vertices
- [x] Add tests and docs
