### ISSUE TITLE
CI/CD pipeline for building repository and docs

### ISSUE THREAD

**Issue by tiuri101** [oopnet/oopnet#4]
## Description
To minimize the effort needed for pushing a new OOPNET version, a CI/CD pipeline would be helpful to automatically:
1) Run tests 
2) Reformat code using [black](https://github.com/psf/black)
3) Build a new Python package and push it to a repository 
4) Build a new docs version and push to host
5) Automatically determine new version number and create changelog (optional: requires semantic-release or something similar)

## Tasks
- [x] Decide on CI/CD pipeline (e.g., [GitHub actions](https://github.com/features/actions))
- [x] Decide whether to use [semantic-release ](https://github.com/semantic-release/semantic-release) and automatic [changelog creation](https://github.com/semantic-release/changelog) or other available plugins for semantic-release
- [x] Implement CI/CD Pipelines
